### ISSUE TITLE
the future of this project

### ISSUE THREAD

**Issue by Kyr4l** [Its-Haze/league-rpc#21]
riot has announced that vanguard will be added to LoL in the next season update (2024). that means LoL will be permanently unplayable on linux as soon as the update drops.
as a result, i am wondering what this project will become once league of linux is dead

**Comment by Bloodiko** [comment]
the idea is to eventually maintain this further, for windows users. 
Only issue currently is leagues own RPC handling. 
We'd need to block that, to override it with this. 
But yea, definitely discouraging.

**Comment by Its-Haze** [comment]
If league is unplayable on linux, then i guess we don't have another choice but to rename this project and mainly focus on windows.. i dont believe this script will trigger vanguard, as it does not modify any game files. It simply uses the leagues client api..


If we manage to block the native league rpc on windows, we will have to be careful and not to trigger vanguard (if files need to be modified)

I will keep maintaining it for as long as league works on linux, and switch focus towards windows users if/when vanguard comes 🙁

**Comment by Its-Haze** [comment]
@Bloodiko @Kyr4l 

Around 20 minutes ago, or so, a new version of League-rpc was released. Yes, no longer `league-rpc-linux`
So the answer to your question again. This project will still be maintained, for windows users.

I have managed to disable the native league rich presence, during startup of the league client. So that is now a feature of `v2.0.0`

Thank you for submitting this issue :)
