### ISSUE TITLE
App does not override League rich precense

### ISSUE THREAD

**Issue by DereC4** [Its-Haze/league-rpc#24]
![image](https://github.com/Its-Haze/league-rpc-linux/assets/53978637/9fa20d50-1883-4200-9646-ace35d726aae)

It looks like this doesn't show above the discord rich precense; any help?

**Comment by Its-Haze** [comment]
@DereC4 
Yes. You can disable the native rich presence by doing this manually.

Assuming you're using Windows:

1. Open Riot games client (not league)
2. While it being open, and you're note logged in to league itself. Do the following
3. Find your league plugins folder, and open the "plugin-manifest.json" file.
    example path: "C:\Riot Games\League of Legends\Plugins\plugin-manifest.json"
4. Delete the block of json, holding the "rcp-be-lol-discord-rp"
![image](https://github.com/Its-Haze/league-rpc-linux/assets/90850836/4f4be1d4-b2fa-40d2-8458-a99ad310a094)
5. Save the file
6. Now from the Riot client, continue by starting league and logging in.

Native discord rpc should be disabled Until the next time you open up the league client.


I sort of have a way to automatically do this everytime you start my program, but the user must have the Riot client open.. A fix for that will eventually be rolled out.

**Comment by DereC4** [comment]
kk

**Comment by Its-Haze** [comment]
@DereC4  After https://github.com/Its-Haze/league-rpc/pull/27 has been merged, and v2.0.0 has been released. The native league presence will automatically be disabled, if this application is launched before the league client. 

Note that v2.0.0 expects the use of Windows, and no longer Linux.. Since that's not a supported platform for League of legends anymore.
It does not mean that this project won't work on linux, it might.. I just won't test there and make sure it works.

So if you're on linux, keep using the version before v2.0.0. for as long as league works on linux.

**Comment by DereC4** [comment]
neat!
