### ISSUE TITLE
Doesn't seem to run with League of legends

### ISSUE THREAD

**Issue by DereC4** [Its-Haze/league-rpc#35]
It appears you have to open the game separately entirely, which is a bit of a shame.

Is this intended behavior for this app? Or is it supposed to open the League of Legends game along with it? 

It's such a great feature, what your custom RPC does, that if this isn't already in I'd like it to be considered.

**Comment by Its-Haze** [comment]
Hi, thanks for the feedback!

Currently, it does not start the game client itself. I understand that it's a feature that would be nice to have.

I mostly didn't want to add this in because it requires the user to specify the full path of the league client, if it's not found in it's default location.
I want this app to be able to start independent of the status of league, meaning that you should be able to start this app even if you are in the middle of a game.

So a few things would be needed here

A new optional argument `--launch-league`. If no path is given, it will check the default/most common place where league should be installed. And only if the client is not running, it will launch, otherwise it will proceed as it does now.

If a path is given, like `--launch-league=<path-to-client>`, then it will of course use that file path instead.

I will look and see what i can cook up.

Please let me know if you have suggestions or other things that might be relevant to this issue. Thanks

//Haze

**Comment by DereC4** [comment]
yea i figure most people would want to have the app basically run with the league rpc, so that's my idea

**Comment by Its-Haze** [comment]
Hi @DereC4  , I hope this new release finds you well. I have added the feature for league to automatically launch when you start this application.

By default, it will look at the default installation path for league of legends. But if you happen to have installed league in a different drive, Then please specify the full path to the client executable.
Instructions on this are in the Readme.

Let me know how it works for you! :)

**Comment by DereC4** [comment]
kk i'll take a look

**Comment by Its-Haze** [comment]
Hi @DereC4 , Hope all is well.

Do you have any feedback on the implementation?
Does it work for you?, Is it working any good?

Thanks
// Haze

**Comment by DereC4** [comment]
works pretty well thanks
