### ISSUE TITLE
error discord running

### ISSUE THREAD

**Issue by marcelohenrique0** [Its-Haze/league-rpc#56]
If discord is already open before opening the program it displays this error attached, for it to work perfectly you need to close discord and only open it after the program is running

![356785740-0beba533-ff64-4668-99a5-cf03d3ec43d4](https://github.com/user-attachments/assets/eccd2126-931f-43c0-8960-63382a12367d)

**Comment by Its-Haze** [comment]
Hi. What version of LeagueRPC are you using?

**Comment by marcelohenrique0** [comment]
> Hi. What version of LeagueRPC are you using?

I'm using the last version 2.3.0

**Comment by Its-Haze** [comment]
The error you've attached does not have much to do with discord itself.
Is there any other logs you receive? it would help to see the full output of the application.

It looks like the application thought that the League client was live and ready to be used, but the summoner icon data was not properly recieved.

Try:
1. Have discord opened.
2. Start league of legends, and wait for it to fully launch
3. Start LeagueRPC (This might result in the native discord RPC to still be active)
4. Observe the application logs.

If you still get the same error, let me know. But in theory, you shouldn't see it if your league client is fully loaded.

What you could do is start LeagueRPC, and allow it to launch League for you (to automatically disable the native rpc) Then if you get this error, just restart LeagueRPC (and keep the league client opened)

**Comment by marcelohenrique0** [comment]
There is no way to start League of Legends before LeaguerPC because it displays this message in the log
![image](https://github.com/user-attachments/assets/b1dc6d6d-71bf-4db0-9c34-9d46a3f5fb18)
-----------------------------------------------------------------------------------------------------------------------------------------------

Your last tip worked exactly as it says in the cmd log, thanks!!!
![image](https://github.com/user-attachments/assets/3f09faf4-8902-4312-b039-56f185d89cf5)

**Comment by Its-Haze** [comment]
@marcelohenrique0  You can start LeagueRPC -- Let it launch league for you. Then when league client is opened (The rpc should be disabled at this point) You can then close LeagueRPC window, and start it up again.
- It will not launch a new league instance
- The native RPC will still be kept disabled, because Riot only repairs the discord plugin during launch of league.

This should ensure that native rpc is still disabled, and when your league client is fully loaded, leagueRPC should be able to function for you.

**Comment by Its-Haze** [comment]
@marcelohenrique0 Also, please use **Windows Terminal** 
And set it as your default terminal. Otherwise you will not see any colors in the output, and the logs will look weird, as they do in the screenshot

Windows Terminal: https://apps.microsoft.com/detail/9n0dx20hk701?hl=en-US&gl=US
Set as default: https://devblogs.microsoft.com/commandline/windows-terminal-as-your-default-command-line-experience/
