### ISSUE TITLE
Add an auto detect for D drive as well

### ISSUE THREAD

**Issue by DereC4** [Its-Haze/league-rpc#62]
Since the next most commonly installed location for the game is in the D:// drive, i was wondering if we could do something like that
so we wouldn't need to specify flags for launch for the D drive if it is in the default location there.

Could make things easier on the client's side

**Comment by Its-Haze** [comment]
Not a bad idea!

**Comment by DereC4** [comment]
ye

**Comment by DereC4** [comment]
any luck on this?

**Comment by Its-Haze** [comment]
@DereC4 I've not had time to work on league-rpc for a while now due to work. Will look into it when i can. 
In the meantime, you should be able to create a shortcut that points to the league-rpc.exe file, and add your arguments there

![image](https://github.com/user-attachments/assets/cef50860-18eb-452f-ab46-9b051c63c28a)

![image](https://github.com/user-attachments/assets/9cd41b95-446c-449d-b8b2-7f4d450b06f8)

![image](https://github.com/user-attachments/assets/6df72b71-6f6c-4f13-9098-d87ad40d4aa8)

Just add ` --launch-league "D:\\Riot Games\\Riot Client\\RiotClientServices.exe"` (or whatever the path is) after leagueRPC.exe and you can just launch this shortcut every time.

**Comment by Its-Haze** [comment]
@DereC4 `v3.1.0` is now released, and includes this feature request as well. Let me know if it works for you :)

**Comment by DereC4** [comment]
ty! I'll take a look when i got time

**Comment by DereC4** [comment]
yup it works, ty @Its-Haze
